### ISSUE TITLE
### Cerrar sesión

### ISSUE THREAD

**Issue by IselaReyesPerdomo94** [IselaReyesPerdomo94/BurguerQueenPandemonium#27]
- [x] Yo como usuario quiero poder cerrar sesión desde el Home
- [x] Quiero cerrar sesión desde el sidebar dentro de cada módulo.

**Comment by LedaHuerta** [comment]
Cierra sesión y redirige a Login desde:
  *Home: FlatButton: Cerrar Sesión
  *Menu: Icon: Cerrar Sesión
  *SideDrawer: icon y span : Cerrar Sesión

**Comment by LedaHuerta** [comment]
Cierra sesión y redirige a Login desde:
*Home: FlatButton: Cerrar Sesión
*Menu: Icon: Cerrar Sesión
*SideDrawer: icon y span : Cerrar Sesión
